stages:
  - main

main:
  stage: main
  image: maven:3.6.3-jdk-8
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  cache:
    paths:
      - .m2/repository
  script:
    - GPG_FILE=`find / -name xuxiaowei_0x97A36125_SECRET`
    - echo $GPG_FILE
    - gpg --import $GPG_FILE
    - SETTINGS_FILE=`find / -name settings.xml`
    - echo $SETTINGS_FILE
    # 使用用户名/密码
    # - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>&#" $SETTINGS_FILE
    # 使用Token
    # 个人访问令牌：https://issues.sonatype.org/secure/ViewProfile.jspa
    # 使用个人访问令牌：https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html
    - sed -i "s#</servers>#<server><id>ossrh</id><configuration><httpHeaders><property><name>Authorization</name><value>Bearer $ossrh_token</value></property></httpHeaders></configuration></server>&#" $SETTINGS_FILE
    - git --version
    - NAME=`mvn help:evaluate -Dexpression=project.name -q -DforceStdout`
    - VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
    - PACKAGING=`mvn help:evaluate -Dexpression=project.packaging -q -DforceStdout`
    - echo 名称：$NAME
    - echo 版本：$VERSION
    - echo 包：$PACKAGING
    - echo 常量网址：https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo 当前分支：$CI_COMMIT_BRANCH
    - echo 主分支：$CI_DEFAULT_BRANCH
    - echo 项目路径：$CI_PROJECT_DIR
    - mvn clean -U package source:jar javadoc:jar deploy -Pgpg -DskipTests && echo 发布完成
  artifacts:
    paths:
      - target/spring-boot-starter-alipay-miniprogram-*
  rules:
    - if: $CI_COMMIT_TAG
